title: Rikard Larsson - DrakirL # your name (or website title) here
logo: "/images/Headset.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  ​I Just Like Making Games :) <br>
  <a href="https://drakirl.github.io/about_me">About Me</a> 
  <br><br>
  <a href="https://drakirl.itch.io/">View My Itch Profile</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/rikard-l-116709114/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
